name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Mongo
      uses: yog27ray/mongo-inmemory-action@v1.1.0
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: MONGODB_CONNECTION_STRING=mongodb://localhost:27017/test;MONGODB_DATABASE=test go test -v ./...
